# Generated by Django 3.2.10 on 2022-04-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'catergory', 'verbose_name_plural': 'categories'},
        ),
    ]
